import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin,AiFillYoutube } from 'react-icons/ai';
import Image from "next/image"
import  Images from '/public/Images.jpg'





export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-2xl font-bold'>Sammienator</h1>
            <ul className='flex items-center'>
              <li>
               <BsFillMoonStarsFill className='cursor-pointer'/>
              </li>
              <li>
                <a className=' bg-gradient-to-r  from-cyan-500  to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume </a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>
              Samuel Mugo
            </h2>
            <h3 className='text-2xl py-2'>
              Developer and Designer.
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800'> Freelance lorem ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. </p>

          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>

          </div>

          <div className='relative rounded-full mx-auto bg-gradient-to-b from-teal-500 w-80 h-80 mt-20'>
            <Image className='rounded-full overflow-hidden' src={Images
            } layout="fill" objectFit='cover' />

          </div>
         
        </section>




        <section>
          <div>
            <h3 className='text-3xl py-1'>
              Services I offer
            </h3>
            <p className='text-md py-2 leading-8 text-gray-800'> 
            Freelance lorem ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. 
            <span className='text-teal-500'> Agencies</span> Freelance lorem ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. <span className='text-teal-500'> Startups</span>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            
            
            </p>
            <p className='text-md py-2 leading-8 text-gray-800'> 
            Freelance lorem ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>

            

          </div>
        </section>
      </main>
    </>
  )
}
